// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://aukgiqyxijydrohltvwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1a2dpcXl4aWp5ZHJvaGx0dnd1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI3MDEwMDYsImV4cCI6MjA2ODI3NzAwNn0.2iVT-7WbxFZ1a0SIh3XDIdBxFRyYI3_w0hu9eRJyjzg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});